"""Report service: orchestrates data collection, rendering and persistence."""

from __future__ import annotations

import shutil
from pathlib import Path

from auth.authorization import Permissions, require_permission
from core.config import AppConfig
from core.constants import EventType, Severity
from core.exceptions import RecordNotFoundError, ReportError
from core.logger import get_logger
from core.utils import utc_now_iso
from core.validators import sanitize_text
from data.models import ReportRecord, User
from data.repositories import ReportRepository
from reports.report_generator import ReportData, ReportGenerator, collect_report_data
from data.repositories import AlertRepository, EventRepository, ScanRepository

log = get_logger("services.report")

VALID_FORMATS = ("TXT", "HTML", "JSON")
VALID_TYPES = ("FULL_ASSESSMENT", "SCAN_REPORT")


class ReportService:
    def __init__(self, reports: ReportRepository, scans: ScanRepository,
                 events: EventRepository, alerts: AlertRepository,
                 config: AppConfig, event_processor):
        self.repo = reports
        self.scans = scans
        self.events = events
        self.alerts = alerts
        self.config = config
        self.processor = event_processor
        self.generator = ReportGenerator()

    @require_permission(Permissions.GENERATE_REPORT)
    def generate(
        self,
        actor: User,
        title: str,
        *,
        report_type: str = "FULL_ASSESSMENT",
        period_days: int = 7,
        scan_id: int | None = None,
        content_format: str = "TXT",
    ) -> ReportRecord:
        title = sanitize_text(title, 120) or "Security Assessment"
        if content_format.upper() not in VALID_FORMATS:
            raise ReportError(f"Format must be one of {VALID_FORMATS}.")
        if report_type not in VALID_TYPES:
            raise ReportError(f"Report type must be one of {VALID_TYPES}.")
        if report_type == "SCAN_REPORT" and scan_id is None:
            raise ReportError("A scan must be selected for a scan report.")
        if report_type == "FULL_ASSESSMENT" and not (1 <= period_days <= 365):
            raise ReportError("Period must be between 1 and 365 days.")

        data: ReportData = collect_report_data(
            self.scans, self.events, self.alerts,
            period_days=period_days, scan_id=scan_id,
        )
        data.title = title
        data.generated_by = actor.username
        data.report_type = report_type

        rendered = self.generator.render(data, content_format.upper())
        file_path = self._write_file(data, rendered, content_format.upper())

        record = ReportRecord(
            title=title,
            report_type=report_type,
            generated_by=actor.username,
            generated_at=utc_now_iso(),
            content_format=content_format.upper(),
            file_path=str(file_path),
            summary=data.summary,
            data=self.generator.to_json_dict(data),
        )
        self.repo.create_report(record)

        self.processor.submit(
            EventType.REPORT_GENERATED, "reporting",
            f"Report '{title}' ({report_type}) generated by {actor.username}",
            Severity.INFO, username=actor.username, details={"report_id": record.id},
        )
        log.info("Report #%s '%s' written to %s", record.id, title, file_path)
        return record

    @require_permission(Permissions.VIEW_REPORTS)
    def list_reports(self, actor: User) -> list[ReportRecord]:
        return self.repo.list_reports()

    @require_permission(Permissions.VIEW_REPORTS)
    def get_report_content(self, actor: User, report_id: int) -> tuple[ReportRecord, str]:
        record = self.repo.get_report(report_id)
        if record is None:
            raise RecordNotFoundError(f"Report #{report_id} not found.")
        content = self._read_file(record.file_path)
        if content is None:
            # File removed on disk — re-render from the stored snapshot.
            from reports.report_generator import ReportGenerator
            content = ReportGenerator().render_from_json(record.data, record.content_format)
        return record, content

    @require_permission(Permissions.DELETE_REPORT)
    def delete_report(self, actor: User, report_id: int) -> None:
        record = self.repo.get_report(report_id)
        if record is None:
            raise RecordNotFoundError(f"Report #{report_id} not found.")
        try:
            Path(record.file_path).unlink(missing_ok=True)
        except OSError:
            log.warning("Could not remove report file %s", record.file_path)
        self.repo.delete_report(report_id)
        self.processor.submit(
            EventType.REPORT_EXPORTED, "reporting",
            f"Report '{record.title}' deleted by {actor.username}",
            Severity.INFO, username=actor.username, internal=True,
        )

    @require_permission(Permissions.VIEW_REPORTS)
    def export_report(self, actor: User, report_id: int, destination: str) -> str:
        record = self.repo.get_report(report_id)
        if record is None:
            raise RecordNotFoundError(f"Report #{report_id} not found.")
        dest = Path(destination)
        if dest.is_dir():
            dest = dest / Path(record.file_path).name
        try:
            shutil.copyfile(record.file_path, dest)
        except (OSError, shutil.SameFileError) as exc:
            raise ReportError(f"Export failed: {exc}") from exc
        self.processor.submit(
            EventType.REPORT_EXPORTED, "reporting",
            f"Report '{record.title}' exported to {dest} by {actor.username}",
            Severity.INFO, username=actor.username,
        )
        return str(dest)

    def stats(self) -> dict:
        return {
            "count": self.repo.count_reports(),
            "last_generated": self.repo.last_generated_at(),
        }

    # ------------------------------------------------------------- internals

    def _write_file(self, data: ReportData, content: str, fmt: str) -> Path:
        directory = Path(self.config.reports_dir)
        try:
            directory.mkdir(parents=True, exist_ok=True)
            path = directory / self.generator.filename_for(data, fmt)
            path.write_text(content, encoding="utf-8")
        except OSError as exc:
            raise ReportError(f"Could not write report file: {exc}") from exc
        return path

    @staticmethod
    def _read_file(path: str) -> str | None:
        try:
            return Path(path).read_text(encoding="utf-8")
        except OSError:
            return None
